export const routeUrls = {
  login: 'login',
  register: 'register',
  homepage: 'products-catalog',
  popular: 'popular',
  checkout: 'checkout',
  auctions: 'auctions',
  products: 'products',
  deliveries: 'deliveries',
  delivery: 'delivery/:id',
  productsCatalog: 'products-catalog',
  productDetails: 'products-catalog/:id',
  adminEmployee: 'admin-manage',
  adminEdit: 'admin-edit',
  adminAdd: 'admin-add',
  comparisons: 'comparison',
  addProduct: 'add',
  shoppingCart: 'shopping-cart',
  confirmRegistration: 'confirm-registration',
  editProduct: 'edit/:id',
  manageProducts: 'manage/products',
  userProfile: 'user-profile',
};
