export const routeUrls = {
  login: 'login',
  register: 'register',
  homepage: 'product-catalog',
  popular: 'popular',
  checkout: 'checkout',
  auctions: 'auctions',
  products: 'products',
  deliveries: 'deliveries',
  delivery: 'delivery/:id',
  productCatalog: 'product-catalog',
  productDetails: 'product-catalog/:id',
  adminEmployee: 'admin-manage',
  adminEdit: 'admin-edit/:id',
  adminAdd: 'admin-add',
  comparisons: 'comparison',
  addProduct: 'add',
  addAuction: 'add-auction',
  shoppingCart: 'shopping-cart',
  confirmRegistration: 'confirm-registration',
  editProduct: 'edit/:id',
  editAuction: 'edit-auction',
  manageProducts: 'manage/products',
  userProfile: 'user-profile',
};
