export const routeUrls = {
  login: 'login',
  register: 'register',
  homepage: 'products',
  popular: 'popular',
  checkout: 'checkout',
  accessories: 'accessories',
  auctions: 'auctions',
  products: 'products',
  productDetails: 'products/:id',
  adminEmployee: 'admin-manage',
  adminEdit: 'admin-edit',
  adminAdd: 'admin-add',
  comparisons: 'comparison',
  addProduct: 'add',
  shoppingCart: 'shopping-cart',
  confirmRegistration: 'confirm-registration',
  editProduct: 'edit/:id',
  manageProducts: 'manage/products',
};
